### PR TITLE
Issue #32: Content suggestions for about / welcome text

### PR DESCRIPTION
**Pull request by brianking**
Signed-off-by: Brian King <brian.king@eclipse-foundation.org>

A pass through the text and have some minor suggestions. The main one is not using the term 'Eclipse Theia Blueprint product' andf replacing it with just 'Eclipse Theia Blueprint'.

### CODE REVIEW

**Review by koegel — APPROVED** [review]
Looks good to me, thanks!

**Comment by koegel** [comment]
@jfaltermeier These changes should also be replicated to the download page once the [initial PR](https://github.com/eclipse-theia/theia-website/pull/133) is accepted there.

**Comment by koegel** [comment]
@thegecko Could you please review and accept this PR, thanks!

**Review by thegecko — APPROVED** [review]
LGTM

**Comment by koegel** [comment]
Thank you, @thegecko!

**Comment by marcdumais-work** [comment]
@thegecko Please merge at your convenience

**Pull request merged**
